#!/usr/bin/python
# -*- coding: utf-8 -*-


''' Copyright 2012-2021 Smartling, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this work except in compliance with the License.
 * You may obtain a copy of the License in the LICENSE file, or at:
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limit
 '''
import os, sys
sys.path.append(os.path.abspath('../'))

import json
import collections
from ApiSource import ApiSource
from smartlingApiSdk.HttpClient import HttpClient
from smartlingApiSdk.Logger import Logger
import logging

class ApiBuilder:
    """
    builds api based in openapi description for specific Api familiy defined as apiName
    """
    def __init__(self, apiName):
        self.apiName = apiName
        json_dict = self.getApiJson()
        self.apisrc = ApiSource(self.apiName)
        self.apisrc.collectMethods(json_dict)

    def getApiJson(self):
        http_loader = HttpClient('api-reference.smartling.com')
        response_data, status_code, headers = http_loader.getHttpResponseAndStatus('GET', '/swagger.json', {})
        if 200 != status_code:
            raise Exception('Can not load openapi description')

        open("openapi3.json",'w').write(response_data.decode('utf8'))
        json_string = response_data
        json_dict = json.loads(json_string, object_pairs_hook=collections.OrderedDict)
        return json_dict

    def build(self):
        built = self.apisrc.build()
        name = self.apiName.replace(' ','').replace('&','')
        outPath = '../smartlingApiSdk/%sApiAutoGenerated.py' % name
        open(outPath,'w').write(built)
        print (built)
        print ("stored as:",outPath)

    def buildExample(self):
        built = self.apisrc.buildExample()
        name = self.apiName.replace(' ','').replace('&','')
        outPath = '../example/%sExample.py' % name
        open(outPath,'w').write(built)
        print (built)
        print ("stored as:",outPath)



def main():
    sys.stdout = Logger('python-sdk', logging.INFO)
    ApiBuilder("Files").build()
    ApiBuilder("Account & Projects").build()
    ApiBuilder("Jobs").build()
    ApiBuilder("Jobs").buildExample()



main()